// AUTO-GENERATED by scripts/gen-changelog.mjs — do not edit by hand.
// Add a "更新: <中文一句话>" trailer (optionally "Changelog-EN: <English>") to a
// commit, then run `npm run changelog` to refresh this file.

export interface ChangelogEntry {
  version: string;
  date: string;
  zh: string;
  en: string;
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    "version": "1.19.0",
    "date": "2026-07-09",
    "zh": "账户概览新增卡玛比率",
    "en": "Added Calmar ratio to account overview"
  },
  {
    "version": "1.18.0",
    "date": "2026-07-08",
    "zh": "实时行情新增 ETH 与恒生指数",
    "en": "Added ETH and Hang Seng Index to live market ticker"
  },
  {
    "version": "1.17.0",
    "date": "2026-07-08",
    "zh": "损益曲线与行情数据源优化",
    "en": "Improved PnL curves and market data sources"
  },
  {
    "version": "1.16.0",
    "date": "2026-07-08",
    "zh": "历史成交、持仓明细与当前委托展示对齐 Hyperliquid",
    "en": "Aligned trade history, positions and open orders with Hyperliquid"
  },
  {
    "version": "1.15.0",
    "date": "2026-07-08",
    "zh": "账户概览补充夏普比率、运行天数与平均持仓时长",
    "en": "Added account overview metrics such as Sharpe ratio, running days and average holding time"
  },
  {
    "version": "1.14.0",
    "date": "2026-07-08",
    "zh": "风控状态与历史成交平仓方式完善",
    "en": "Improved risk status and trade close method labels"
  },
  {
    "version": "1.13.0",
    "date": "2026-07-08",
    "zh": "实时更新指示移到标题栏Live Account后面",
    "en": "Moved the live indicator next to Live Account"
  },
  {
    "version": "1.12.0",
    "date": "2026-07-08",
    "zh": "首页标题改用毛笔楷书字体",
    "en": "Switched the hero title to a brush calligraphy font"
  },
  {
    "version": "1.11.0",
    "date": "2026-07-08",
    "zh": "行情卡新增EMA20与RSI技术指标",
    "en": "Added EMA20/RSI indicators to the market ticker"
  },
  {
    "version": "1.10.0",
    "date": "2026-07-07",
    "zh": "行情新增美元指数DXY",
    "en": "Added the US Dollar Index (DXY) to the market ticker"
  },
  {
    "version": "1.9.0",
    "date": "2026-07-07",
    "zh": "行情新增日经225和韩国综合指数",
    "en": "Added Nikkei 225 and KOSPI to the market ticker"
  },
  {
    "version": "1.8.0",
    "date": "2026-07-07",
    "zh": "首页定位介绍改为竖排三行",
    "en": "Restyled the hero tagline as three stacked lines"
  },
  {
    "version": "1.7.0",
    "date": "2026-07-07",
    "zh": "精简页脚信息",
    "en": "Simplified the footer"
  },
  {
    "version": "1.6.0",
    "date": "2026-07-07",
    "zh": "页脚新增版本号与更新日志",
    "en": "Added version badge and changelog to the footer"
  },
  {
    "version": "1.5.0",
    "date": "2026-07-07",
    "zh": "修复损益曲线并新增累积资金费",
    "en": "PnL range fixes and net funding stat"
  },
  {
    "version": "1.4.0",
    "date": "2026-07-06",
    "zh": "新增可折叠委托历史模块",
    "en": "Added collapsible order history"
  },
  {
    "version": "1.3.0",
    "date": "2026-07-05",
    "zh": "首页重设计并支持多币种计价",
    "en": "Hero redesign and multi-currency equity"
  },
  {
    "version": "1.2.0",
    "date": "2026-07-03",
    "zh": "扩充行情指数与交易绩效指标",
    "en": "More market tickers and trade metrics"
  },
  {
    "version": "1.1.0",
    "date": "2026-07-02",
    "zh": "新增昼夜主题与损益周期切换",
    "en": "Added theme toggle and PnL ranges"
  },
  {
    "version": "1.0.0",
    "date": "2026-07-01",
    "zh": "接入实盘账户，看板上线",
    "en": "Live account dashboard launched"
  }
];
