// AUTO-GENERATED by scripts/gen-changelog.mjs — do not edit by hand.
// Add a "更新: <中文一句话>" trailer (optionally "Changelog-EN: <English>") to a
// commit, then run `npm run changelog` to refresh this file.

export interface ChangelogEntry {
  version: string;
  date: string;
  zh: string;
  en: string;
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    "version": "1.33.0",
    "date": "2026-07-16",
    "zh": "本周范围改为周一至周日",
    "en": "Fixed weekly calendar range"
  },
  {
    "version": "1.32.0",
    "date": "2026-07-16",
    "zh": "本月范围改为月初至月末",
    "en": "Fixed monthly calendar range"
  },
  {
    "version": "1.31.0",
    "date": "2026-07-16",
    "zh": "修复本月数据与本周相同",
    "en": "Fixed monthly calendar data"
  },
  {
    "version": "1.30.0",
    "date": "2026-07-16",
    "zh": "优化事件翻译，保留人名地名",
    "en": "Optimized event translation"
  },
  {
    "version": "1.29.0",
    "date": "2026-07-16",
    "zh": "经济事件支持智能关键词翻译",
    "en": "Added keyword-based translation"
  },
  {
    "version": "1.28.0",
    "date": "2026-07-16",
    "zh": "补充PPI月率中文翻译",
    "en": "Added PPI m/m translation"
  },
  {
    "version": "1.27.0",
    "date": "2026-07-16",
    "zh": "经济日历新增状态筛选",
    "en": "Economic calendar now supports released/pending/all status filter"
  },
  {
    "version": "1.26.0",
    "date": "2026-07-16",
    "zh": "补充经济事件中文翻译",
    "en": "Added economic event translations"
  },
  {
    "version": "1.25.0",
    "date": "2026-07-16",
    "zh": "经济日历新增本周/本月切换",
    "en": "Added week/month toggle"
  },
  {
    "version": "1.24.0",
    "date": "2026-07-16",
    "zh": "经济日历事件支持中英文切换",
    "en": "Added Chinese/English toggle"
  },
  {
    "version": "1.23.0",
    "date": "2026-07-16",
    "zh": "优化页脚行间距与字体",
    "en": "Improved footer spacing"
  },
  {
    "version": "1.22.0",
    "date": "2026-07-16",
    "zh": "账户概览指标添加悬停提示",
    "en": "Added metric tooltips"
  },
  {
    "version": "1.21.0",
    "date": "2026-07-16",
    "zh": "修正历史成交平仓方式的判定口径",
    "en": "Corrected close-method classification in trade history"
  },
  {
    "version": "1.20.0",
    "date": "2026-07-09",
    "zh": "账户概览新增交易期望值",
    "en": "Added trade expectancy to account overview"
  },
  {
    "version": "1.19.0",
    "date": "2026-07-09",
    "zh": "账户概览新增卡玛比率",
    "en": "Added Calmar ratio to account overview"
  },
  {
    "version": "1.18.0",
    "date": "2026-07-08",
    "zh": "实时行情新增 ETH 与恒生指数",
    "en": "Added ETH and Hang Seng Index to live market ticker"
  },
  {
    "version": "1.17.0",
    "date": "2026-07-08",
    "zh": "损益曲线与行情数据源优化",
    "en": "Improved PnL curves and market data sources"
  },
  {
    "version": "1.16.0",
    "date": "2026-07-08",
    "zh": "交易展示对齐Hyperliquid",
    "en": "Aligned with Hyperliquid"
  },
  {
    "version": "1.15.0",
    "date": "2026-07-08",
    "zh": "账户概览补充夏普比率等指标",
    "en": "Added Sharpe ratio metrics"
  },
  {
    "version": "1.14.0",
    "date": "2026-07-08",
    "zh": "风控状态与历史成交平仓方式完善",
    "en": "Improved risk status and trade close method labels"
  },
  {
    "version": "1.13.0",
    "date": "2026-07-08",
    "zh": "实时指示移到标题栏",
    "en": "Moved live indicator"
  },
  {
    "version": "1.12.0",
    "date": "2026-07-08",
    "zh": "首页标题改用毛笔楷书字体",
    "en": "Switched the hero title to a brush calligraphy font"
  },
  {
    "version": "1.11.0",
    "date": "2026-07-08",
    "zh": "行情卡新增EMA20与RSI技术指标",
    "en": "Added EMA20/RSI indicators to the market ticker"
  },
  {
    "version": "1.10.0",
    "date": "2026-07-07",
    "zh": "行情新增美元指数DXY",
    "en": "Added the US Dollar Index (DXY) to the market ticker"
  },
  {
    "version": "1.9.0",
    "date": "2026-07-07",
    "zh": "行情新增日经225和韩国综合指数",
    "en": "Added Nikkei 225 and KOSPI to the market ticker"
  },
  {
    "version": "1.8.0",
    "date": "2026-07-07",
    "zh": "首页定位介绍改为竖排三行",
    "en": "Restyled the hero tagline as three stacked lines"
  },
  {
    "version": "1.7.0",
    "date": "2026-07-07",
    "zh": "精简页脚信息",
    "en": "Simplified the footer"
  },
  {
    "version": "1.6.0",
    "date": "2026-07-07",
    "zh": "页脚新增版本号与更新日志",
    "en": "Added version badge and changelog to the footer"
  },
  {
    "version": "1.5.0",
    "date": "2026-07-07",
    "zh": "修复损益曲线并新增累积资金费",
    "en": "PnL range fixes and net funding stat"
  },
  {
    "version": "1.4.0",
    "date": "2026-07-06",
    "zh": "新增可折叠委托历史模块",
    "en": "Added collapsible order history"
  },
  {
    "version": "1.3.0",
    "date": "2026-07-05",
    "zh": "首页重设计并支持多币种计价",
    "en": "Hero redesign and multi-currency equity"
  },
  {
    "version": "1.2.0",
    "date": "2026-07-03",
    "zh": "扩充行情指数与交易绩效指标",
    "en": "More market tickers and trade metrics"
  },
  {
    "version": "1.1.0",
    "date": "2026-07-02",
    "zh": "新增昼夜主题与损益周期切换",
    "en": "Added theme toggle and PnL ranges"
  },
  {
    "version": "1.0.0",
    "date": "2026-07-01",
    "zh": "接入实盘账户，看板上线",
    "en": "Live account dashboard launched"
  }
];
